/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.MappingDispatchAction;

import com.vcs.struts.form.InsertStudentForm;
import com.vcs.struts.form.UpdateStudentForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-30-2014
 * 
 * XDoclet definition:
 * @struts.action path="/insertStudent" name="insertStudentForm" input="/insertStudent.jsp" parameter="insert" scope="request" validate="true"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class StudentAction extends MappingDispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward insert(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		InsertStudentForm insertStudentForm = (InsertStudentForm) form;
		System.out.println("insert");
		return mapping.findForward("success");
	}
	public ActionForward update(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UpdateStudentForm updateStudentForm = (UpdateStudentForm) form;
		System.out.println("update");
		return mapping.findForward("success");
	}
}