/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.form;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-05-2014
 * 
 * XDoclet definition:
 * @struts.form name="studentForm"
 */
public class StudentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** studentNo property */
	private String studentNo;

	/** studentName property */
	private String studentName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the studentNo.
	 * @return String
	 */
	public String getStudentNo() {
		return studentNo;
	}

	/** 
	 * Set the studentNo.
	 * @param studentNo The studentNo to set
	 */
	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	/** 
	 * Returns the studentName.
	 * @return String
	 */
	public String getStudentName() {
		return studentName;
	}

	/** 
	 * Set the studentName.
	 * @param studentName The studentName to set
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}
}