/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import java.lang.reflect.InvocationTargetException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.sun.org.apache.commons.beanutils.BeanUtils;
import com.vcs.struts.dao.FloorDao;
import com.vcs.struts.floor.Floor;
import com.vcs.struts.form.FloorForm;

public class FloorCreateAction extends Action {
	
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		FloorForm floorForm = (FloorForm) form;
		System.out.println("floorCreateAction");
		Floor floor=new Floor();
		try {
			BeanUtils.copyProperties(floor, floorForm);
		} catch (IllegalAccessException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (InvocationTargetException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		FloorDao floorDao=new FloorDao();
		String status=null;
		
		try {
			status=floorDao.floorCreate(floor);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		request.setAttribute("status", status);
		
		return mapping.findForward("success");
	}
}