/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 01-30-2014
 * 
 * XDoclet definition:
 * @struts.form name="updateStudentForm"
 */
public class UpdateStudentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** studentNo property */
	private String studentNo;

	/** studentName property */
	private String studentName;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Returns the studentNo.
	 * @return String
	 */
	public String getStudentNo() {
		return studentNo;
	}

	/** 
	 * Set the studentNo.
	 * @param studentNo The studentNo to set
	 */
	public void setStudentNo(String studentNo) {
		this.studentNo = studentNo;
	}

	/** 
	 * Returns the studentName.
	 * @return String
	 */
	public String getStudentName() {
		return studentName;
	}

	/** 
	 * Set the studentName.
	 * @param studentName The studentName to set
	 */
	public void setStudentName(String studentName) {
		this.studentName = studentName;
	}
}