/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.ActionMessage;
import org.apache.struts.action.DynaActionForm;

/**
 * MyEclipse Struts Creation date: 01-27-2014
 * 
 * XDoclet definition:
 * 
 * @struts.action path="/student" name="studentForm" input="/student.jsp"
 *                scope="request" validate="true"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class StudentAction extends Action {
	/*
	 * Generated Methods
	 */

	/**
	 * Method execute
	 * 
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm studentForm = (DynaActionForm) form;
		System.out.println("StudentName:" + studentForm.getString("studentNo"));
		System.out.println("StudentName:"
				+ studentForm.getString("studentName"));

		ActionErrors ae = new ActionErrors();

		if (studentForm.getString("studentNo").equals("")
				|| null == studentForm.getString("studentNo")) {
			ae.add("studentNo", new ActionMessage("errors.required",
					"studentNo"));
		}
		if (studentForm.getString("studentName").equals("")
				|| null == studentForm.getString("studentName")) {
			ae.add("studentName", new ActionMessage("errors.required",
					"studentName"));
		}
		if (!ae.isEmpty()) {
			saveErrors(request, ae);
			return mapping.getInputForward();
		} else {
			return mapping.findForward("success");
		}
	}
}