/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import java.io.InputStream;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.upload.FormFile;

import com.vcs.struts.form.StudentForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-05-2014
 * 
 * XDoclet definition:
 * @struts.action path="/student" name="studentForm" input="/student.jsp" scope="request" validate="true"
 * @struts.action-forward name="success" path="/success.jsp"
 */
public class StudentAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StudentForm studentForm = (StudentForm) form;
		FormFile fileUpload=studentForm.getFileUpload();
		
		System.out.println("Content type:"+fileUpload.getContentType());
		System.out.println("FileName:"+fileUpload.getFileName());
		System.out.println("FileSize:"+fileUpload.getFileSize());
		
		try {
			System.out.println("FileData:"+fileUpload.getFileData());
			InputStream fileUploadStream=fileUpload.getInputStream();
			//read the data from inputstream and write o outputstream/DB
			//filenet etc
			System.out.println("FileUploadStream:"+fileUploadStream);
		} catch (Exception e) {
			System.out.println("Exception:"+e);
		}
		return mapping.findForward("success");
	}
}