/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

/** 
 * MyEclipse Struts
 * Creation date: 01-05-2014
 * 
 * XDoclet definition:
 * @struts.form name="studentForm"
 */
public class StudentForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** fileUpload property */
	private FormFile fileUpload;

	/*
	 * Generated Methods
	 */

	/** 
	 * Returns the fileUpload.
	 * @return FormFile
	 */
	public FormFile getFileUpload() {
		return fileUpload;
	}

	/** 
	 * Set the fileUpload.
	 * @param fileUpload The fileUpload to set
	 */
	public void setFileUpload(FormFile fileUpload) {
		this.fileUpload = fileUpload;
	}
}