/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.form;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.validator.ValidatorForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-23-2012
 * 
 * XDoclet definition:
 * @struts.form name="studentForm"
 */
public class StudentForm extends ValidatorForm {
	/*
	 * Generated fields
	 */

	/** studentno property */
	private String studentno;

	/** studentname property */
	private String studentname;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	
	/** 
	 * Returns the studentno.
	 * @return String
	 */
	public String getStudentno() {
		return studentno;
	}

	/** 
	 * Set the studentno.
	 * @param studentno The studentno to set
	 */
	public void setStudentno(String studentno) {
		this.studentno = studentno;
	}

	/** 
	 * Returns the studentname.
	 * @return String
	 */
	public String getStudentname() {
		return studentname;
	}

	/** 
	 * Set the studentname.
	 * @param studentname The studentname to set
	 */
	public void setStudentname(String studentname) {
		this.studentname = studentname;
	}
}