/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vcs.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import com.vcs.struts.form.EmployeeForm;

/** 
 * MyEclipse Struts
 * Creation date: 01-01-2014
 * 
 * XDoclet definition:
 * @struts.action path="/employee" name="employeeForm" input="/employee.jsp" parameter="/employee.jsp" scope="request" validate="true"
 */
public class EmployeeAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		EmployeeForm employeeForm = (EmployeeForm) form;// TODO Auto-generated method stub
		return mapping.findForward("success");
	}
}